version: '3.1'

services:

  db:
    image: postgres:12
    restart: on-failure
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

# version: '3'
# services:
#     zookeeper:
#         image: wurstmeister/zookeeper
 
#     kafka:
#         image: wurstmeister/kafka:2.13-2.7.1
#         ports:
#         - "9092:9092"
#         environment:
#             KAFKA_ADVERTISED_HOST_NAME: localhost
#             KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181