// Code generated by sqlc. DO NOT EDIT.

package psql

import (
	"time"
)

type Event struct {
	ID           int64
	UserID       int64
	Description  string
	ScheduledFor time.Time
	CreatedAt    time.Time
}

type Note struct {
	ID          int64
	UserID      int64
	Description string
	CreatedAt   time.Time
}

type Task struct {
	ID          int64
	Done        bool
	Description string
	UserID      int64
	CreatedAt   time.Time
}

type User struct {
	ID       int64
	Username string
	Fullname string
}
